apiVersion: 1

contactPoints:
  - orgId: 1
    name: Telegram Alerts
    receivers:
      - uid: telegram-alerts
        type: telegram
        disableResolveMessage: false
        settings:
          bottoken: !!str "${GF_ALERT_TELEGRAM_BOT_TOKEN}"
          chatid: "-5030685707"
          message: |
            {{ template "todo.telegram.message" . }}
